# ???: Use docker publisher instead of Docker Hub autobuilds?

before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.buildType=gr
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X main.buildTime={{ .Date }}

archives:
  - format: binary
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      386: 32bit
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^[Tt]ypo"
